spring.application.name=url-shortener
server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${POSTGRES_DB:url_shortener}
spring.datasource.username=${POSTGRES_USER:url_shortener}
spring.datasource.password=${POSTGRES_PASSWORD:local_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

app.rate-limit.requests=${RATE_LIMIT_REQUESTS:10}
app.rate-limit.window-seconds=${RATE_LIMIT_WINDOW_SECONDS:60}
app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:change-this-local-password}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
