CREATE TABLE url_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url_id BIGINT NOT NULL,
    visited_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_url_visits_short_url
        FOREIGN KEY (short_url_id) REFERENCES short_urls (id) ON DELETE CASCADE
);

CREATE INDEX ix_url_visits_short_url_id ON url_visits (short_url_id);
